-- START TRANSACTION
-- BEGIN
START TRANSACTION ISOLATION LEVEL SERIALIZABLE;
-- Do normal SQL commands here
COMMIT;


START TRANSACTION ISOLATION LEVEL SERIALIZABLE;
-- Do normal SQL commands here
ROLLBACK;


START TRANSACTION ISOLATION LEVEL SERIALIZABLE, READ ONLY, DEFERRABLE;
-- SELECT statements for backups here
COMMIT; --BEGIN;
